### ISSUE TITLE
Cocoapods 1.5 and CocoaImageHashing.h not found

### ISSUE THREAD

**Issue by dflateau** [ameingast/cocoaimagehashing#12]
Has anyone had a problem with Cocoapods 1.5 when using

#import <CocoaImageHashing/CocoaImageHashing.h>

getting a file not found when building? I tried all the usual tricks of cleaning, deleting derived data, updating, reinstalling the pod - to no avail.

UPDATE: [This comment](https://github.com/ameingast/cocoaimagehashing/issues/9#issuecomment-281932175) on a a closed issue solved my problem - even though I'm using Objective-C. I'm also using Cocoapods 1.5 and XCode 9.3. Perhaps a new issue that has creeped in to Cocoapod installation?

**Comment by xll503721** [comment]
the same question

**Comment by ameingast** [comment]
Try replacing `#import <CocoaImageHashing/CocoaImageHashing.h>` with `@import CocoaImageHashing;`. 

I'm not sure why, but Cocoapods seems to mess up the search path for the framework.

**Comment by ameingast** [comment]
I tracked it down to an issue in the Podspec file. It should be fixed in release [1.6.1](https://github.com/ameingast/cocoaimagehashing/tree/1.6.1) and 113ef4591b89b758eae6868533cf3b788d9d4157.
