### ISSUE TITLE
Can you add example in swift too?

### ISSUE THREAD

**Issue by kuls14** [ameingast/cocoaimagehashing#18]
I am having trouble in understanding Obj c code. If you can make this code available in swift it'll be so helpful.

**Comment by bizibizi** [comment]
@kuls14  did you got it? can you share?

**Comment by kuls14** [comment]
@bizibizi no, I have not. Hopefully @ameingast will update documentation soon.

**Comment by danshev** [comment]
```
import CocoaImageHashing

class ViewController: UIViewController {
    
    let myHasher = OSImageHashing.sharedInstance()

    // Sometime later
    let myImage = UIImage(named: "image-asset-name")
    let myHashValue = myHasher.hashImage(myImage!, with: .pHash)

}
```

**Comment by ameingast** [comment]
There are some examples in the playground. If you need help on more specific use cases, let me know and I'll try to improve it there.

Thanks!
